// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservaDeChaleMvc.Data;

#nullable disable

namespace ReservaDeChaleMvc.Migrations
{
    [DbContext(typeof(ReservaDbContext))]
    [Migration("20240220202004_ChaleMvc")]
    partial class ChaleMvc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ReservaDeChaleMvc.Models.ChaleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Chale")
                        .HasColumnType("int");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("QuantidadeDePessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reserve");
                });
#pragma warning restore 612, 618
        }
    }
}
